name: utopic_toast
description: Toast Flutter package. You can call it whenever you need it. Showing multiple dismissible toasts at the same time with showing and hiding animation.
version: 1.0.0
homepage: https://github.com/utopicnarwhal

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">2.0.0"

dependencies:
  rxdart:
  provider:

  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
