name: utopic_toast
description: Toast Flutter package. You can call it whenever you need it. Showing multiple dismissible toasts at the same time with showing and hiding animation.
version: 0.1.0
homepage: https://github.com/utopicnarwhal

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.8 <2.0.0"

dependencies:
  rxdart: ^0.23.1
  provider: ^4.0.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
