name: utopic_toast
description: Toast Flutter package.
version: 0.0.1+1
author: Sergei Danilov
homepage: https://github.com/utopicnarwhal

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.8 <2.0.0"

dependencies:
  rxdart: ^0.23.1
  provider: ^4.0.4

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
